name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
          - system: aarch64-linux
          - system: armv7l-linux

    steps:
      - name: Maximize disk space (part 1)
        uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - name: Maximize disk space (part 2)
        run: |
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /home/linuxbrew
          sudo rm -rf /home/runner/.rustup
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/lib/heroku
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /var/lib/docker/overlay2

      - name: Install system dependencies
        run: |
          sudo apt update -y
          sudo apt install -y cpulimit qemu-user-static

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: |
            log-lines = 500

      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Set up Attic
        uses: ErrorNoInternet/attic-action@v0

      - name: Set up Cachix
        uses: cachix/cachix-action@v12
        with:
          name: errornobinaries

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build package
        run: nix build --system ${{ matrix.system }} -L .#package
